// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: DailyTaskFilterCityReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CmdId: 111
// EnetChannelId: 0
// EnetIsReliable: true
// IsAllowClient: true
type DailyTaskFilterCityReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CityId uint32 `protobuf:"varint,8,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
}

func (x *DailyTaskFilterCityReq) Reset() {
	*x = DailyTaskFilterCityReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DailyTaskFilterCityReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DailyTaskFilterCityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyTaskFilterCityReq) ProtoMessage() {}

func (x *DailyTaskFilterCityReq) ProtoReflect() protoreflect.Message {
	mi := &file_DailyTaskFilterCityReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyTaskFilterCityReq.ProtoReflect.Descriptor instead.
func (*DailyTaskFilterCityReq) Descriptor() ([]byte, []int) {
	return file_DailyTaskFilterCityReq_proto_rawDescGZIP(), []int{0}
}

func (x *DailyTaskFilterCityReq) GetCityId() uint32 {
	if x != nil {
		return x.CityId
	}
	return 0
}

var File_DailyTaskFilterCityReq_proto protoreflect.FileDescriptor

var file_DailyTaskFilterCityReq_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31,
	0x0a, 0x16, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x69, 0x74, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_DailyTaskFilterCityReq_proto_rawDescOnce sync.Once
	file_DailyTaskFilterCityReq_proto_rawDescData = file_DailyTaskFilterCityReq_proto_rawDesc
)

func file_DailyTaskFilterCityReq_proto_rawDescGZIP() []byte {
	file_DailyTaskFilterCityReq_proto_rawDescOnce.Do(func() {
		file_DailyTaskFilterCityReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_DailyTaskFilterCityReq_proto_rawDescData)
	})
	return file_DailyTaskFilterCityReq_proto_rawDescData
}

var file_DailyTaskFilterCityReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_DailyTaskFilterCityReq_proto_goTypes = []interface{}{
	(*DailyTaskFilterCityReq)(nil), // 0: DailyTaskFilterCityReq
}
var file_DailyTaskFilterCityReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_DailyTaskFilterCityReq_proto_init() }
func file_DailyTaskFilterCityReq_proto_init() {
	if File_DailyTaskFilterCityReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_DailyTaskFilterCityReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DailyTaskFilterCityReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_DailyTaskFilterCityReq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DailyTaskFilterCityReq_proto_goTypes,
		DependencyIndexes: file_DailyTaskFilterCityReq_proto_depIdxs,
		MessageInfos:      file_DailyTaskFilterCityReq_proto_msgTypes,
	}.Build()
	File_DailyTaskFilterCityReq_proto = out.File
	file_DailyTaskFilterCityReq_proto_rawDesc = nil
	file_DailyTaskFilterCityReq_proto_goTypes = nil
	file_DailyTaskFilterCityReq_proto_depIdxs = nil
}
