// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: InBattleMechanicusStageType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InBattleMechanicusStageType int32

const (
	InBattleMechanicusStageType_IN_BATTLE_MECHANICUS_STAGE_TYPE_NONE      InBattleMechanicusStageType = 0
	InBattleMechanicusStageType_IN_BATTLE_MECHANICUS_STAGE_TYPE_BUILD     InBattleMechanicusStageType = 1
	InBattleMechanicusStageType_IN_BATTLE_MECHANICUS_STAGE_TYPE_CARD_FLIP InBattleMechanicusStageType = 2
	InBattleMechanicusStageType_IN_BATTLE_MECHANICUS_STAGE_TYPE_KILL      InBattleMechanicusStageType = 3
)

// Enum value maps for InBattleMechanicusStageType.
var (
	InBattleMechanicusStageType_name = map[int32]string{
		0: "IN_BATTLE_MECHANICUS_STAGE_TYPE_NONE",
		1: "IN_BATTLE_MECHANICUS_STAGE_TYPE_BUILD",
		2: "IN_BATTLE_MECHANICUS_STAGE_TYPE_CARD_FLIP",
		3: "IN_BATTLE_MECHANICUS_STAGE_TYPE_KILL",
	}
	InBattleMechanicusStageType_value = map[string]int32{
		"IN_BATTLE_MECHANICUS_STAGE_TYPE_NONE":      0,
		"IN_BATTLE_MECHANICUS_STAGE_TYPE_BUILD":     1,
		"IN_BATTLE_MECHANICUS_STAGE_TYPE_CARD_FLIP": 2,
		"IN_BATTLE_MECHANICUS_STAGE_TYPE_KILL":      3,
	}
)

func (x InBattleMechanicusStageType) Enum() *InBattleMechanicusStageType {
	p := new(InBattleMechanicusStageType)
	*p = x
	return p
}

func (x InBattleMechanicusStageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InBattleMechanicusStageType) Descriptor() protoreflect.EnumDescriptor {
	return file_InBattleMechanicusStageType_proto_enumTypes[0].Descriptor()
}

func (InBattleMechanicusStageType) Type() protoreflect.EnumType {
	return &file_InBattleMechanicusStageType_proto_enumTypes[0]
}

func (x InBattleMechanicusStageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InBattleMechanicusStageType.Descriptor instead.
func (InBattleMechanicusStageType) EnumDescriptor() ([]byte, []int) {
	return file_InBattleMechanicusStageType_proto_rawDescGZIP(), []int{0}
}

var File_InBattleMechanicusStageType_proto protoreflect.FileDescriptor

var file_InBattleMechanicusStageType_proto_rawDesc = []byte{
	0x0a, 0x21, 0x49, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x4d, 0x65, 0x63, 0x68, 0x61, 0x6e,
	0x69, 0x63, 0x75, 0x73, 0x53, 0x74, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2a, 0xcb, 0x01, 0x0a, 0x1b, 0x49, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x4d, 0x65, 0x63, 0x68, 0x61, 0x6e, 0x69, 0x63, 0x75, 0x73, 0x53, 0x74, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x24, 0x49, 0x4e, 0x5f, 0x42, 0x41, 0x54, 0x54, 0x4c, 0x45,
	0x5f, 0x4d, 0x45, 0x43, 0x48, 0x41, 0x4e, 0x49, 0x43, 0x55, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x47,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x29, 0x0a,
	0x25, 0x49, 0x4e, 0x5f, 0x42, 0x41, 0x54, 0x54, 0x4c, 0x45, 0x5f, 0x4d, 0x45, 0x43, 0x48, 0x41,
	0x4e, 0x49, 0x43, 0x55, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x42, 0x55, 0x49, 0x4c, 0x44, 0x10, 0x01, 0x12, 0x2d, 0x0a, 0x29, 0x49, 0x4e, 0x5f, 0x42,
	0x41, 0x54, 0x54, 0x4c, 0x45, 0x5f, 0x4d, 0x45, 0x43, 0x48, 0x41, 0x4e, 0x49, 0x43, 0x55, 0x53,
	0x5f, 0x53, 0x54, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x41, 0x52, 0x44,
	0x5f, 0x46, 0x4c, 0x49, 0x50, 0x10, 0x02, 0x12, 0x28, 0x0a, 0x24, 0x49, 0x4e, 0x5f, 0x42, 0x41,
	0x54, 0x54, 0x4c, 0x45, 0x5f, 0x4d, 0x45, 0x43, 0x48, 0x41, 0x4e, 0x49, 0x43, 0x55, 0x53, 0x5f,
	0x53, 0x54, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4b, 0x49, 0x4c, 0x4c, 0x10,
	0x03, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_InBattleMechanicusStageType_proto_rawDescOnce sync.Once
	file_InBattleMechanicusStageType_proto_rawDescData = file_InBattleMechanicusStageType_proto_rawDesc
)

func file_InBattleMechanicusStageType_proto_rawDescGZIP() []byte {
	file_InBattleMechanicusStageType_proto_rawDescOnce.Do(func() {
		file_InBattleMechanicusStageType_proto_rawDescData = protoimpl.X.CompressGZIP(file_InBattleMechanicusStageType_proto_rawDescData)
	})
	return file_InBattleMechanicusStageType_proto_rawDescData
}

var file_InBattleMechanicusStageType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_InBattleMechanicusStageType_proto_goTypes = []interface{}{
	(InBattleMechanicusStageType)(0), // 0: InBattleMechanicusStageType
}
var file_InBattleMechanicusStageType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_InBattleMechanicusStageType_proto_init() }
func file_InBattleMechanicusStageType_proto_init() {
	if File_InBattleMechanicusStageType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_InBattleMechanicusStageType_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_InBattleMechanicusStageType_proto_goTypes,
		DependencyIndexes: file_InBattleMechanicusStageType_proto_depIdxs,
		EnumInfos:         file_InBattleMechanicusStageType_proto_enumTypes,
	}.Build()
	File_InBattleMechanicusStageType_proto = out.File
	file_InBattleMechanicusStageType_proto_rawDesc = nil
	file_InBattleMechanicusStageType_proto_goTypes = nil
	file_InBattleMechanicusStageType_proto_depIdxs = nil
}
