// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: IslandPartyActivityDetailInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IslandPartyActivityDetailInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unk2800_PDBHCBCLFBM []*Unk2800_MBKLJLMLIKF `protobuf:"bytes,15,rep,name=Unk2800_PDBHCBCLFBM,json=Unk2800PDBHCBCLFBM,proto3" json:"Unk2800_PDBHCBCLFBM,omitempty"`
}

func (x *IslandPartyActivityDetailInfo) Reset() {
	*x = IslandPartyActivityDetailInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IslandPartyActivityDetailInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IslandPartyActivityDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IslandPartyActivityDetailInfo) ProtoMessage() {}

func (x *IslandPartyActivityDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_IslandPartyActivityDetailInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IslandPartyActivityDetailInfo.ProtoReflect.Descriptor instead.
func (*IslandPartyActivityDetailInfo) Descriptor() ([]byte, []int) {
	return file_IslandPartyActivityDetailInfo_proto_rawDescGZIP(), []int{0}
}

func (x *IslandPartyActivityDetailInfo) GetUnk2800_PDBHCBCLFBM() []*Unk2800_MBKLJLMLIKF {
	if x != nil {
		return x.Unk2800_PDBHCBCLFBM
	}
	return nil
}

var File_IslandPartyActivityDetailInfo_proto protoreflect.FileDescriptor

var file_IslandPartyActivityDetailInfo_proto_rawDesc = []byte{
	0x0a, 0x23, 0x49, 0x73, 0x6c, 0x61, 0x6e, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x55, 0x6e, 0x6b, 0x32, 0x38, 0x30, 0x30, 0x5f, 0x4d,
	0x42, 0x4b, 0x4c, 0x4a, 0x4c, 0x4d, 0x4c, 0x49, 0x4b, 0x46, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x66, 0x0a, 0x1d, 0x49, 0x73, 0x6c, 0x61, 0x6e, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x45, 0x0a, 0x13, 0x55, 0x6e, 0x6b, 0x32, 0x38, 0x30, 0x30, 0x5f, 0x50, 0x44, 0x42,
	0x48, 0x43, 0x42, 0x43, 0x4c, 0x46, 0x42, 0x4d, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x55, 0x6e, 0x6b, 0x32, 0x38, 0x30, 0x30, 0x5f, 0x4d, 0x42, 0x4b, 0x4c, 0x4a, 0x4c, 0x4d,
	0x4c, 0x49, 0x4b, 0x46, 0x52, 0x12, 0x55, 0x6e, 0x6b, 0x32, 0x38, 0x30, 0x30, 0x50, 0x44, 0x42,
	0x48, 0x43, 0x42, 0x43, 0x4c, 0x46, 0x42, 0x4d, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_IslandPartyActivityDetailInfo_proto_rawDescOnce sync.Once
	file_IslandPartyActivityDetailInfo_proto_rawDescData = file_IslandPartyActivityDetailInfo_proto_rawDesc
)

func file_IslandPartyActivityDetailInfo_proto_rawDescGZIP() []byte {
	file_IslandPartyActivityDetailInfo_proto_rawDescOnce.Do(func() {
		file_IslandPartyActivityDetailInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_IslandPartyActivityDetailInfo_proto_rawDescData)
	})
	return file_IslandPartyActivityDetailInfo_proto_rawDescData
}

var file_IslandPartyActivityDetailInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_IslandPartyActivityDetailInfo_proto_goTypes = []interface{}{
	(*IslandPartyActivityDetailInfo)(nil), // 0: IslandPartyActivityDetailInfo
	(*Unk2800_MBKLJLMLIKF)(nil),           // 1: Unk2800_MBKLJLMLIKF
}
var file_IslandPartyActivityDetailInfo_proto_depIdxs = []int32{
	1, // 0: IslandPartyActivityDetailInfo.Unk2800_PDBHCBCLFBM:type_name -> Unk2800_MBKLJLMLIKF
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_IslandPartyActivityDetailInfo_proto_init() }
func file_IslandPartyActivityDetailInfo_proto_init() {
	if File_IslandPartyActivityDetailInfo_proto != nil {
		return
	}
	file_Unk2800_MBKLJLMLIKF_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_IslandPartyActivityDetailInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IslandPartyActivityDetailInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_IslandPartyActivityDetailInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_IslandPartyActivityDetailInfo_proto_goTypes,
		DependencyIndexes: file_IslandPartyActivityDetailInfo_proto_depIdxs,
		MessageInfos:      file_IslandPartyActivityDetailInfo_proto_msgTypes,
	}.Build()
	File_IslandPartyActivityDetailInfo_proto = out.File
	file_IslandPartyActivityDetailInfo_proto_rawDesc = nil
	file_IslandPartyActivityDetailInfo_proto_goTypes = nil
	file_IslandPartyActivityDetailInfo_proto_depIdxs = nil
}
