// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: PolygonRegionSize.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolygonRegionSize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PointList []*VectorPlane `protobuf:"bytes,5,rep,name=point_list,json=pointList,proto3" json:"point_list,omitempty"`
	Height    float32        `protobuf:"fixed32,9,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *PolygonRegionSize) Reset() {
	*x = PolygonRegionSize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PolygonRegionSize_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolygonRegionSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolygonRegionSize) ProtoMessage() {}

func (x *PolygonRegionSize) ProtoReflect() protoreflect.Message {
	mi := &file_PolygonRegionSize_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolygonRegionSize.ProtoReflect.Descriptor instead.
func (*PolygonRegionSize) Descriptor() ([]byte, []int) {
	return file_PolygonRegionSize_proto_rawDescGZIP(), []int{0}
}

func (x *PolygonRegionSize) GetPointList() []*VectorPlane {
	if x != nil {
		return x.PointList
	}
	return nil
}

func (x *PolygonRegionSize) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_PolygonRegionSize_proto protoreflect.FileDescriptor

var file_PolygonRegionSize_proto_rawDesc = []byte{
	0x0a, 0x17, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53,
	0x69, 0x7a, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x11,
	0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x2b, 0x0a, 0x0a, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x6c,
	0x61, 0x6e, 0x65, 0x52, 0x09, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PolygonRegionSize_proto_rawDescOnce sync.Once
	file_PolygonRegionSize_proto_rawDescData = file_PolygonRegionSize_proto_rawDesc
)

func file_PolygonRegionSize_proto_rawDescGZIP() []byte {
	file_PolygonRegionSize_proto_rawDescOnce.Do(func() {
		file_PolygonRegionSize_proto_rawDescData = protoimpl.X.CompressGZIP(file_PolygonRegionSize_proto_rawDescData)
	})
	return file_PolygonRegionSize_proto_rawDescData
}

var file_PolygonRegionSize_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PolygonRegionSize_proto_goTypes = []interface{}{
	(*PolygonRegionSize)(nil), // 0: PolygonRegionSize
	(*VectorPlane)(nil),       // 1: VectorPlane
}
var file_PolygonRegionSize_proto_depIdxs = []int32{
	1, // 0: PolygonRegionSize.point_list:type_name -> VectorPlane
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PolygonRegionSize_proto_init() }
func file_PolygonRegionSize_proto_init() {
	if File_PolygonRegionSize_proto != nil {
		return
	}
	file_VectorPlane_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_PolygonRegionSize_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolygonRegionSize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PolygonRegionSize_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PolygonRegionSize_proto_goTypes,
		DependencyIndexes: file_PolygonRegionSize_proto_depIdxs,
		MessageInfos:      file_PolygonRegionSize_proto_msgTypes,
	}.Build()
	File_PolygonRegionSize_proto = out.File
	file_PolygonRegionSize_proto_rawDesc = nil
	file_PolygonRegionSize_proto_goTypes = nil
	file_PolygonRegionSize_proto_depIdxs = nil
}
