// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: SetCoopChapterViewedReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CmdId: 1965
// EnetChannelId: 0
// EnetIsReliable: true
// IsAllowClient: true
type SetCoopChapterViewedReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChapterId uint32 `protobuf:"varint,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
}

func (x *SetCoopChapterViewedReq) Reset() {
	*x = SetCoopChapterViewedReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SetCoopChapterViewedReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetCoopChapterViewedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCoopChapterViewedReq) ProtoMessage() {}

func (x *SetCoopChapterViewedReq) ProtoReflect() protoreflect.Message {
	mi := &file_SetCoopChapterViewedReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCoopChapterViewedReq.ProtoReflect.Descriptor instead.
func (*SetCoopChapterViewedReq) Descriptor() ([]byte, []int) {
	return file_SetCoopChapterViewedReq_proto_rawDescGZIP(), []int{0}
}

func (x *SetCoopChapterViewedReq) GetChapterId() uint32 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

var File_SetCoopChapterViewedReq_proto protoreflect.FileDescriptor

var file_SetCoopChapterViewedReq_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x56, 0x69, 0x65, 0x77, 0x65, 0x64, 0x52, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x38, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x56, 0x69, 0x65, 0x77, 0x65, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SetCoopChapterViewedReq_proto_rawDescOnce sync.Once
	file_SetCoopChapterViewedReq_proto_rawDescData = file_SetCoopChapterViewedReq_proto_rawDesc
)

func file_SetCoopChapterViewedReq_proto_rawDescGZIP() []byte {
	file_SetCoopChapterViewedReq_proto_rawDescOnce.Do(func() {
		file_SetCoopChapterViewedReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_SetCoopChapterViewedReq_proto_rawDescData)
	})
	return file_SetCoopChapterViewedReq_proto_rawDescData
}

var file_SetCoopChapterViewedReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SetCoopChapterViewedReq_proto_goTypes = []interface{}{
	(*SetCoopChapterViewedReq)(nil), // 0: SetCoopChapterViewedReq
}
var file_SetCoopChapterViewedReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SetCoopChapterViewedReq_proto_init() }
func file_SetCoopChapterViewedReq_proto_init() {
	if File_SetCoopChapterViewedReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_SetCoopChapterViewedReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetCoopChapterViewedReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SetCoopChapterViewedReq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SetCoopChapterViewedReq_proto_goTypes,
		DependencyIndexes: file_SetCoopChapterViewedReq_proto_depIdxs,
		MessageInfos:      file_SetCoopChapterViewedReq_proto_msgTypes,
	}.Build()
	File_SetCoopChapterViewedReq_proto = out.File
	file_SetCoopChapterViewedReq_proto_rawDesc = nil
	file_SetCoopChapterViewedReq_proto_goTypes = nil
	file_SetCoopChapterViewedReq_proto_depIdxs = nil
}
