// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: SumoDungeonAvatar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SumoDungeonAvatar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvatarGuid uint64 `protobuf:"varint,11,opt,name=avatar_guid,json=avatarGuid,proto3" json:"avatar_guid,omitempty"`
	IsAlive    bool   `protobuf:"varint,13,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	IsTrial    bool   `protobuf:"varint,4,opt,name=is_trial,json=isTrial,proto3" json:"is_trial,omitempty"`
}

func (x *SumoDungeonAvatar) Reset() {
	*x = SumoDungeonAvatar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SumoDungeonAvatar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SumoDungeonAvatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumoDungeonAvatar) ProtoMessage() {}

func (x *SumoDungeonAvatar) ProtoReflect() protoreflect.Message {
	mi := &file_SumoDungeonAvatar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumoDungeonAvatar.ProtoReflect.Descriptor instead.
func (*SumoDungeonAvatar) Descriptor() ([]byte, []int) {
	return file_SumoDungeonAvatar_proto_rawDescGZIP(), []int{0}
}

func (x *SumoDungeonAvatar) GetAvatarGuid() uint64 {
	if x != nil {
		return x.AvatarGuid
	}
	return 0
}

func (x *SumoDungeonAvatar) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

func (x *SumoDungeonAvatar) GetIsTrial() bool {
	if x != nil {
		return x.IsTrial
	}
	return false
}

var File_SumoDungeonAvatar_proto protoreflect.FileDescriptor

var file_SumoDungeonAvatar_proto_rawDesc = []byte{
	0x0a, 0x17, 0x53, 0x75, 0x6d, 0x6f, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6a, 0x0a, 0x11, 0x53, 0x75, 0x6d,
	0x6f, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x1f,
	0x0a, 0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x47, 0x75, 0x69, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x69, 0x73, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73,
	0x5f, 0x74, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73,
	0x54, 0x72, 0x69, 0x61, 0x6c, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SumoDungeonAvatar_proto_rawDescOnce sync.Once
	file_SumoDungeonAvatar_proto_rawDescData = file_SumoDungeonAvatar_proto_rawDesc
)

func file_SumoDungeonAvatar_proto_rawDescGZIP() []byte {
	file_SumoDungeonAvatar_proto_rawDescOnce.Do(func() {
		file_SumoDungeonAvatar_proto_rawDescData = protoimpl.X.CompressGZIP(file_SumoDungeonAvatar_proto_rawDescData)
	})
	return file_SumoDungeonAvatar_proto_rawDescData
}

var file_SumoDungeonAvatar_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SumoDungeonAvatar_proto_goTypes = []interface{}{
	(*SumoDungeonAvatar)(nil), // 0: SumoDungeonAvatar
}
var file_SumoDungeonAvatar_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SumoDungeonAvatar_proto_init() }
func file_SumoDungeonAvatar_proto_init() {
	if File_SumoDungeonAvatar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_SumoDungeonAvatar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SumoDungeonAvatar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SumoDungeonAvatar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SumoDungeonAvatar_proto_goTypes,
		DependencyIndexes: file_SumoDungeonAvatar_proto_depIdxs,
		MessageInfos:      file_SumoDungeonAvatar_proto_msgTypes,
	}.Build()
	File_SumoDungeonAvatar_proto = out.File
	file_SumoDungeonAvatar_proto_rawDesc = nil
	file_SumoDungeonAvatar_proto_goTypes = nil
	file_SumoDungeonAvatar_proto_depIdxs = nil
}
