// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: ViewCodexReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CmdId: 4202
// EnetChannelId: 0
// EnetIsReliable: true
// IsAllowClient: true
type ViewCodexReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeDataList []*CodexTypeData `protobuf:"bytes,10,rep,name=type_data_list,json=typeDataList,proto3" json:"type_data_list,omitempty"`
}

func (x *ViewCodexReq) Reset() {
	*x = ViewCodexReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ViewCodexReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewCodexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewCodexReq) ProtoMessage() {}

func (x *ViewCodexReq) ProtoReflect() protoreflect.Message {
	mi := &file_ViewCodexReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewCodexReq.ProtoReflect.Descriptor instead.
func (*ViewCodexReq) Descriptor() ([]byte, []int) {
	return file_ViewCodexReq_proto_rawDescGZIP(), []int{0}
}

func (x *ViewCodexReq) GetTypeDataList() []*CodexTypeData {
	if x != nil {
		return x.TypeDataList
	}
	return nil
}

var File_ViewCodexReq_proto protoreflect.FileDescriptor

var file_ViewCodexReq_proto_rawDesc = []byte{
	0x0a, 0x12, 0x56, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x43, 0x6f, 0x64, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x0c, 0x56, 0x69, 0x65,
	0x77, 0x43, 0x6f, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x12, 0x34, 0x0a, 0x0e, 0x74, 0x79, 0x70,
	0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x0c, 0x74, 0x79, 0x70, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_ViewCodexReq_proto_rawDescOnce sync.Once
	file_ViewCodexReq_proto_rawDescData = file_ViewCodexReq_proto_rawDesc
)

func file_ViewCodexReq_proto_rawDescGZIP() []byte {
	file_ViewCodexReq_proto_rawDescOnce.Do(func() {
		file_ViewCodexReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_ViewCodexReq_proto_rawDescData)
	})
	return file_ViewCodexReq_proto_rawDescData
}

var file_ViewCodexReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ViewCodexReq_proto_goTypes = []interface{}{
	(*ViewCodexReq)(nil),  // 0: ViewCodexReq
	(*CodexTypeData)(nil), // 1: CodexTypeData
}
var file_ViewCodexReq_proto_depIdxs = []int32{
	1, // 0: ViewCodexReq.type_data_list:type_name -> CodexTypeData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ViewCodexReq_proto_init() }
func file_ViewCodexReq_proto_init() {
	if File_ViewCodexReq_proto != nil {
		return
	}
	file_CodexTypeData_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ViewCodexReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewCodexReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ViewCodexReq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ViewCodexReq_proto_goTypes,
		DependencyIndexes: file_ViewCodexReq_proto_depIdxs,
		MessageInfos:      file_ViewCodexReq_proto_msgTypes,
	}.Build()
	File_ViewCodexReq_proto = out.File
	file_ViewCodexReq_proto_rawDesc = nil
	file_ViewCodexReq_proto_goTypes = nil
	file_ViewCodexReq_proto_depIdxs = nil
}
