// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: WorldOwnerDailyTaskNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CmdId: 102
// EnetChannelId: 0
// EnetIsReliable: true
// IsAllowClient: true
type WorldOwnerDailyTaskNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterCityId uint32           `protobuf:"varint,2,opt,name=filter_city_id,json=filterCityId,proto3" json:"filter_city_id,omitempty"`
	TaskList     []*DailyTaskInfo `protobuf:"bytes,1,rep,name=task_list,json=taskList,proto3" json:"task_list,omitempty"`
}

func (x *WorldOwnerDailyTaskNotify) Reset() {
	*x = WorldOwnerDailyTaskNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WorldOwnerDailyTaskNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorldOwnerDailyTaskNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldOwnerDailyTaskNotify) ProtoMessage() {}

func (x *WorldOwnerDailyTaskNotify) ProtoReflect() protoreflect.Message {
	mi := &file_WorldOwnerDailyTaskNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldOwnerDailyTaskNotify.ProtoReflect.Descriptor instead.
func (*WorldOwnerDailyTaskNotify) Descriptor() ([]byte, []int) {
	return file_WorldOwnerDailyTaskNotify_proto_rawDescGZIP(), []int{0}
}

func (x *WorldOwnerDailyTaskNotify) GetFilterCityId() uint32 {
	if x != nil {
		return x.FilterCityId
	}
	return 0
}

func (x *WorldOwnerDailyTaskNotify) GetTaskList() []*DailyTaskInfo {
	if x != nil {
		return x.TaskList
	}
	return nil
}

var File_WorldOwnerDailyTaskNotify_proto protoreflect.FileDescriptor

var file_WorldOwnerDailyTaskNotify_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x44, 0x61, 0x69, 0x6c,
	0x79, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x13, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x19, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x12, 0x24, 0x0a, 0x0e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x69,
	0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x43, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x09, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x44,
	0x61, 0x69, 0x6c, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x74, 0x61,
	0x73, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_WorldOwnerDailyTaskNotify_proto_rawDescOnce sync.Once
	file_WorldOwnerDailyTaskNotify_proto_rawDescData = file_WorldOwnerDailyTaskNotify_proto_rawDesc
)

func file_WorldOwnerDailyTaskNotify_proto_rawDescGZIP() []byte {
	file_WorldOwnerDailyTaskNotify_proto_rawDescOnce.Do(func() {
		file_WorldOwnerDailyTaskNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_WorldOwnerDailyTaskNotify_proto_rawDescData)
	})
	return file_WorldOwnerDailyTaskNotify_proto_rawDescData
}

var file_WorldOwnerDailyTaskNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_WorldOwnerDailyTaskNotify_proto_goTypes = []interface{}{
	(*WorldOwnerDailyTaskNotify)(nil), // 0: WorldOwnerDailyTaskNotify
	(*DailyTaskInfo)(nil),             // 1: DailyTaskInfo
}
var file_WorldOwnerDailyTaskNotify_proto_depIdxs = []int32{
	1, // 0: WorldOwnerDailyTaskNotify.task_list:type_name -> DailyTaskInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_WorldOwnerDailyTaskNotify_proto_init() }
func file_WorldOwnerDailyTaskNotify_proto_init() {
	if File_WorldOwnerDailyTaskNotify_proto != nil {
		return
	}
	file_DailyTaskInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_WorldOwnerDailyTaskNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorldOwnerDailyTaskNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_WorldOwnerDailyTaskNotify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_WorldOwnerDailyTaskNotify_proto_goTypes,
		DependencyIndexes: file_WorldOwnerDailyTaskNotify_proto_depIdxs,
		MessageInfos:      file_WorldOwnerDailyTaskNotify_proto_msgTypes,
	}.Build()
	File_WorldOwnerDailyTaskNotify_proto = out.File
	file_WorldOwnerDailyTaskNotify_proto_rawDesc = nil
	file_WorldOwnerDailyTaskNotify_proto_goTypes = nil
	file_WorldOwnerDailyTaskNotify_proto_depIdxs = nil
}
